print("------------------------------------LIST------------------------------------------------------")
a=["cricket","bike","food"]
print("MAIN LIST",a)
a.append("LOVE")
print("APPEND",a)
a.extend(["GOOD","BAD"])
print("EXTEND",a)
a.insert(2,"Friendship")
print("INSERT",a)
a.pop(1)
print("POP",a)
a.reverse()
print("REVERSE",a)
print("------------------------------------DICT------------------------------------------------------")
Dict={'1':'Cricket', '2':'Food', '3':'Bike'}
First_value= Dict.setdefault('1')
print("Dictionary:", Dict) 
print("First_value:",First_value) 
Fourth_value= Dict.setdefault('4','MONEY')
print("Fourth_value:",Fourth_value)
print("------------------------------------SETS------------------------------------------------------")
print('2011 ICC-WORLDCUP-FINAL SCORECARD FOR TEAM-INDIA')
def Player(name,score,balls_faced):
    print(name,'has scored-',score,'outof-',balls_faced)
Player(name='V SEWAGH',score='0',balls_faced='2') 
Player(name='SACHIN TENDULKAR',score='18',balls_faced='14')
Player(name='G GAMBHIR',score='97',balls_faced='122') 
Player(name='VIRAT KOHLI',score='35',balls_faced='49') 
Player(name='M.S.DHONI*',score='91',balls_faced='79') 
Player(name='YUARAJ_SINGH*',score='21',balls_faced='24')     
print("------------------------------------TUPLE------------------------------------------------------")
string = "Let's Upgrade-PYTHON" 
tuple = tuple(string) 
print(tuple)
